<?php
namespace app\models;

use Yii;
use dektrium\user\models\Profile as BaseProfile;

class Profile extends BaseProfile {

    public $img;

    public function rules() {
        $rules = parent::rules();
        $rules[] = [['img'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, gif']; // uploaded file validation
        $rules[] = [['image_id'], 'integer'];
        return $rules;
    }

    public function attributeLabels()
    {
        $labels = parent::attributeLabels(); // TODO: Change the autogenerated stub

        $labels['img'] = Yii::t('user', 'Select Profile Picture');
        $labels['image_id'] = Yii::t('user', 'Profile Picture');

        return $labels;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImage() {
        return $this->hasOne(Image::className(), ['id' => 'image_id']);
    }
}

?>